name: project build & test

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: "target/*.jar"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Run tests and verify
        run: mvn clean verify
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_PORT: ${{ secrets.RABBIT_PORT }}
          RABBIT_USER: ${{ secrets.RABBIT_USER }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_VHOST: ${{ secrets.RABBIT_VHOST }}

      - name: Generate Jacoco Report
        run: mvn jacoco:report

      - uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: "target/site/jacoco/"
          retention-days: 5
